DjangoEcommerce/AdminModel/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path("", all_esite_details),
    path("get_users_name/", get_users_name),
    path("get_orders/", get_order_by_trns_id),
    path("get_deliverd_or_pending/", get_deliverd_or_pending),
    path("get_address_for_popup/", get_address_forpopup),
    path("cust_detail/<int:id>/", cust_detail, name="cust_detail"),
    path("get_reviews_onstars/", get_reviews_onstars)
]

DjangoEcommerce/EcommerceApp/urls.py
from django.urls import path,include
from .views import paithani,semi_paithani,silk_wear,traditional_wear,western_wear,product_details,searched_products


urlpatterns = [
    path("paithani/", paithani,name="paithani"),
    path("semi_paithani/", semi_paithani,name="semi_paithani"),
    path("silk_saree/", silk_wear,name="silk_saree"),
    path("traditional_wear/", traditional_wear,name="traditional_wear"),
    path("western_wear/", western_wear, name="western_wear"),
    path("product_details/<int:pk>/", product_details, name="product_details"),
    path("searhced_products/",searched_products,name="searched_products")
]

DjangoEcommerce/EcommerceProject/urls.py
from django.contrib import admin
from django.urls import path,include
from EcommerceApp.views import *
from django.conf.urls.static import static
from django.conf import settings


from django.views.static import serve
from django.urls import re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', store, name="store"),
    path("cart/", cart, name="cart"),
    path("signup/", signupForm, name="signup"),
    path("logout/",logoutUser,name="logout"),
    path('login/', loginPage, name="login"),
    path("wears/", include("EcommerceApp.urls")),
    path("update/", update_item, name="update"),
    path("cart/", cart, name="cart"),
    path("chekcout/", checkout, name="checkout"),
    path("process_order/", processOrder, name="process_order"),
    path("update_address/", updateAddress, name="updateAddress"),
    path("update_review/", update_review, name="update_review"),
    path("activate_email/<uidb64>/<token>/", activateEmailAccount, name="activate_email"),
    path("request_reset_email/", RequestResetPasswordView.as_view(), name="request_reset_email"),
    path("set_new_password/<uidb64>/<token>/", SetNewPasswordView.as_view(), name="set_new_password"),
    path("username_validation/", UserNameValidation.as_view(), name="username_validation"),
    path("useremail_validation/", UserEmailValidation.as_view(), name="useremail_validation"),
    path("postalcode_validation/",PostalCodeValidation.as_view(),name="postalcode_validation"),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),

    path("AdminModel/",include('AdminModel.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT) 

DjangoEcommerce/EcommerceApp/models.py
from django.db import models
from django.contrib.auth.models import User

CHOICES = (
    ("paithani", "paithani"),
    ("semi_paithani", "semi_paithani"),
    ("silk_saree", "silk_saree"),
    ("traditional", "traditional"),
    ("western", "western"),
)

IS_AVAILABLE = (("YES", "YES"), ("NO", "NO"))


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    email = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name


class ShippingAddress(models.Model):

    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    phone = models.CharField(max_length=200)
    address = models.TextField()
    zipcode = models.IntegerField()
    city = models.CharField(max_length=80)
    state = models.CharField(max_length=80)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    image = models.ImageField()
    image1 = models.ImageField(null=True,blank=True)
    image2 = models.ImageField(null=True,blank=True)
    image3 = models.ImageField(null=True,blank=True)
    image4 = models.ImageField(null=True,blank=True)
    image5 = models.ImageField(null=True,blank=True)
    image6 = models.ImageField(null=True,blank=True)
    image7 = models.ImageField(null=True,blank=True)
    image8 = models.ImageField(null=True,blank=True)
    image9 = models.ImageField(null=True,blank=True)
    image10 = models.ImageField(null=True,blank=True)
    category = models.CharField(max_length=20, choices=CHOICES)
    is_avaible = models.BooleanField(default=True)
    fabric = models.CharField(max_length=256, blank=True, null=True)
    pattern = models.CharField(max_length=256, blank=True, null=True)
    color = models.CharField(max_length=256, blank=True, null=True)
    style = models.CharField(max_length=256, blank=True, null=True)
    in_the_pack = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def imageurl(self):
        try:
            url = self.image.url
        except:
            url = ""
        return url
    
    @property
    def imagesURL(self):
        images_list = []
        try:
            images_list.append(self.image1.url)
        except:
            return images_list
        try:
            images_list.append(self.image2.url)
        except:
            return images_list
        try:
            images_list.append(self.image3.url)
        except:
            return images_list
        try:
            images_list.append(self.image4.url)
        except:
            return images_list
        try:
            images_list.append(self.image5.url)
        except:
            return images_list
        try:
            images_list.append(self.image6.url)
        except:
            return images_list
        try:
            images_list.append(self.image7.url)
        except:
            return images_list
        try:
            images_list.append(self.image8.url)
        except:
            return images_list
        try:
            images_list.append(self.image9.url)
        except:
            return images_list
        try:
            images_list.append(self.image10.url)
        except:
            return images_list
        return images_list



        
class ProductReview(models.Model):
    
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review = models.CharField(max_length=256,null=True,blank=True)
    stars = models.PositiveIntegerField(null=True,blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return str(self.customer.name)+" : "+ str(self.product.name)
    
class Order(models.Model):

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    date_deliverd = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=200)
    is_deliverd = models.BooleanField(default=False,blank=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    date_ordered = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

DjangoEcommerce/EcommerceApp/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from .models import Customer
from django import forms
import requests

class CreateUserForm(UserCreationForm):
    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
    )
    phone = forms.CharField(validators=[phone_regex], max_length=17)
    address = forms.CharField(widget=forms.Textarea)
    city = forms.CharField(max_length=50)
    zipcode = forms.IntegerField()
    state = forms.CharField(max_length=80)

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "phone",
            "address",
            "city",
            "zipcode",
            "state",
        ]
    def clean_zipcode(self):
        url = "http://127.0.0.1:4545/%d/" % (self.cleaned_data['zipcode'])
        data = requests.get(url)
        data = data.json()
        if data['data']['is_available'] == False:
            raise forms.ValidationError("We are unreachable for pincode : " + str(self.cleaned_data['zipcode']))
        else:
            return self.cleaned_data['zipcode']
        



        
class ShippingAddressForm(forms.ModelForm):
    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
    )
    phone = forms.CharField(validators=[phone_regex], max_length=17)
    class Meta:
        model = ShippingAddress
        fields = [
            'address',
            'phone',
            'city',
            'state',
            'zipcode'
        ]
    def clean_zipcode(self):
        url = "http://127.0.0.1:4545/%d/" % (self.cleaned_data['zipcode'])
        data = requests.get(url)
        data = data.json()
        if data['data']['is_available'] == False:
            raise forms.ValidationError("We are unreachable for pincode : " + str(self.cleaned_data['zipcode']))
        else:
            return self.cleaned_data['zipcode']


        
class CheckPincode(forms.Form):
    Postal_Code = forms.IntegerField()

DjangoEcommerce/templates/EcommerceApp/cart.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
<div class="cart__items cart__items__cart__only">
    <div class="cart__items__elements cart__items__elements__pro">
        <h1><a href="{% url 'checkout' %}">Checkout</a></h1>
        <h1>Item</h1>
        <h1>Price</h1>
        <h1>Quantity</h1>
        <h1>Total</h1>
    </div>
    <div class="cart__items__elements__sub">
        {% for item in items %} 
        <div class="cart__items__elements cart__items__elements__scrolling">
            <div>
                <img class="cart__image__" src="{{item.product.imageurl}}" alt="">
            </div>
            <div>
                <h1>{{item.product.name}}</h1>
            </div>
            <div>
                <h1>{{item.product.price|floatformat:2}}</h1>
            </div>
            <div>
                <div class="up__down__arrows">
                    <div class="up__down__arrows__imgs">
                        <img class="update-cart" data-product={{item.product.id}} data-action="add" src="{% static 'images/uparo.png' %}">
                        <img class="update-cart" data-product={{item.product.id}} data-action="remove" src="{% static 'images/downaro.png' %}">
                    </div>
                    <h1 class="Quantity__h1">x {{item.quantity}}</h1>
                </div>
            </div>
            <div>
                <h1>{{item.get_total|floatformat:2}}</h1>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

DjangoEcommerce/templates/EcommerceApp/checkout.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
{% load checkpayment from templatefilters %}
{% load orderbydate from templatefilters %}


<div class="checkout__page">
    <div class="checkout__page__user__address" id="checkout__page__user__address__id">
        <span class="checkout__page__user__address__close__icon">&#215;</span>
        <span class="checkout__page__user__address__close__icon take__up">&raquo;</span>
        <p>
            Hello {{request.user.customer.name|title}}, your orders will be deliverd at <span id="main__address__here">
                {{form.address.value}},
                {{form.city.value}} - {{form.zipcode.value}}, {{form.state.value}}</span>. 
                <span id="should__not__touch">You can still edit address <a href="{% url 'updateAddress' %}">here</a>.</span>
        </p>
    </div>
    <div class="checkout__products">
        <h1 class="recent__orders">Orders Summary</h1>
        <h2 class="recent__orders__price__info">Items : {{order.get_cart_items}} <br> Total : {{order.get_cart_total|floatformat:2 }}/-</h2>
        <div class="cart__items">
            <div
                class="cart__items__elements display__none__on__mobile checkout__page__only__four cart__items__elements__pro">
                <h1></h1>
                <h1>Item</h1>
                <h1>Quantity</h1>
                <h1>Total</h1>
            </div>
            <hr class="cart__items__elements__after__hr"> <br> <br>
            <div class="scrollable">
                {% for item in items %}
                <div class="cart__items__elements__sub">
                    <div class="cart__items__elements checkout__page__only__four cart__items__elements__scrolling">
                        <div>
                            <img class="cart__image__" src="{{item.product.imageurl}}" alt="">
                        </div>
                        <div>
                            <h1>{{item.product.name}}</h1>
                        </div>
                        <div>
                            <div class="up__down__arrows">
                                <h1 class="Quantity__h1">x {{item.quantity}}</h1>
                            </div>
                        </div>
                        <div>
                            <h1>₹ {{item.get_total|floatformat:2}}/-</h1>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="order__button__div">
                {% if order.get_cart_total|checkpayment %}
                <a id="order-button-checkout" href="{% url 'process_order' %}"  class="order__button">
                    Order Now
                </a>
                {% endif %}
                
            </div>
        </div>
        <h1 class="recent__orders">Recent Orders</h1>
        <div class="cart__items">
            <div class="cart__items__elements display__none__on__mobile cart__items__elements__pro">
                <h1></h1>
                <h1>Item</h1>
                <h1>Transaction ID</h1>
                <h1>Date ordeted</h1>
                <h1>Is deliverd</h1>
            </div>
            <hr class="cart__items__elements__after__hr"> <br> <br>
            <div class="scrollable">

                {% for key,val in recent_orders_dict.items|orderbydate %}
                {% for term in val.product %}
                <div class="cart__items__elements__sub">
                    <div class="cart__items__elements  cart__items__elements__scrolling">
                        <div>
                            <img class="cart__image__" src="{{val.product.0.0.imageurl}}">
                        </div>
                        <div>
                            <h1>{{term.0}} <br> x{{term.1}}</h1>
                            <!-- <h1>{{val.product.1.0.imageurl}} <br> x{{term.1}}</h1> -->

                        </div>
                        <div>
                            <h1><small>{{key.transaction_id}}</small></h1>
                        </div>
                        <div>
                            <h1>{{val.date_ordered}}</h1>
                        </div>
                        <div>
                            <h1>{% if val.is_deliverd %}
                            Yes. On, <br><small>{{val.date_deliverd}}</small>
                            {% else %}
                            Not yet.
                            {% endif %}</h1>
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% endfor %}

            </div>
        </div>

    </div>
</div>


<script>
    function sleep(time) {
        return new Promise((resolve) => setTimeout(resolve, time));
    }
    

    var order_button_checkout = document.getElementById("order-button-checkout")
    var order_button_info = document.getElementById("order-information-checkout")
    order_button_checkout.addEventListener("click", () => {
        $("span#should__not__touch").hide()
        $(".loading-screen").show()
        order_button_checkout.classList.add("hidden")
        order_button_info.classList.remove("hidden")
    })
</script>

{% endblock content %}

DjangoEcommerce/templates/EcommerceApp/login.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
{% load checkloginstring from templatefilters %}

<style>
    .login__page input[type="submit"]{
        cursor: pointer;
        transition:0.4s 
    }
    .login__page input[type="submit"]:hover {
        background-color: orange;
        color: #fff;
    }
</style>
<div class="login__page">

    <div class="login__page__form">
        <h1 class="login__page__form__heading">Login</h1>
        {% for message in messages %}
        {% if message|checkloginstring %}
        <p id="messages" style="color: green;">{{message}}</p>
        {% else %}
        <p id="messages" style="color: red;">{{message}}</p>
        {% endif %}
        {% endfor %} <br>
        <form method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username...">
            <input type="password" type="password" name="password" placeholder="Password...">
            <input href="" type="submit">
        </form>
        <div class="login__page__ask__for__signup__forgotpassowrd">
            <small>Need account ? <a href="{% url 'signup' %}">Signup</a></small>
            <small><a  href="{% url 'request_reset_email' %}">Forgot password ?</a></small>
        </div>
    </div>
</div>
{% endblock %}

DjangoEcommerce/templates/EcommerceApp/middleware.html
{% extends '../base.html' %}
{% block content %}
<style>
    #server_load {
        min-height: 80vh;
        
    }
    #server_load >div {
        width: 100%;
        position: absolute;
        top: 40%;
        left: 50%;
        transform: translate(-50%,-50%  );
    }
     #server_load >div h1 {
         width: 75%;
         text-align: center;
         margin: 0 auto;
         font-weight: bold;
     }
</style>

<div class="text-center" id="server_load">
    <div>
    <h1 style="font-weight: 300;color: orange;">Service is under maintaince. We are very apologize for this.</h1>

    </div>
</div>

{% endblock %}

DjangoEcommerce/templates/EcommerceApp/signup.html
{% extends '../base.html' %}
{% block content %}
{% load static %}

<style>
    .signup__container {
       margin-bottom: 25vh;
    }
    .is-invalid {
        box-shadow: 0px 0px 10px red !important;
    }
    .signup__container__main__signup form input[type="submit"] {
        background: transparent;
        box-shadow: 0px 0px 2px orange;
        cursor: pointer;
        transition: 0.4s;
    }
    .signup__container__main__signup form input[type="submit"]:hover {
        background-color: orange;
        color: #fff;
    }
    .errorlist {
        color: red;
    }
    .signup__container__main__signup textarea {
        width: 100%;
    }
</style>
<div class="signup__container">
    
    <div class="signup__container__main__signup">
        <h1 class="signup__container__main__signup__heading">Signup</h1>
        <form method="POST">
            <p id="valid-the-username" style="color: red; font-size: 10px; margin-bottom: 5px;">
                {{form.errors}}
            </p>
            <p id="valid-the-email" style="color: red; font-size: 10px; margin-bottom: 5px;"></p> <br>
            {% csrf_token %}
            {{form.username}}
            {{form.email}}
            {{form.phone}}
            <div class="signup__container__main__signup__collapse">
                {{form.first_name}}
                {{form.last_name}}
            </div>
            {{form.address}}
            <p id="valid-the-zipcode" style="color: red; font-size: 10px; margin-bottom: 5px;"></p>
            <div class="signup__container__main__signup__collapse">
                {{form.zipcode}}
                {{form.city}}
            </div>
            {{form.state}}  
             {{form.password1}}
             {{form.password2}}
            <input id="regisetering__account" type="submit" value="Register">
        </form>
    </div>

    <div class="signup__container__img">
        <div class="swiper-container1">
            <div class="swiper-wrapper">
                <div class="swiper-slide" style="background-image:url({% static 'images/girls/sunny2.jpg' %})"></div>
                <div class="swiper-slide" style="background-image:url({% static 'images/girls/3.jpg' %})"></div>
                <div class="swiper-slide" style="background-image:url({% static 'images/girls/4.jpg' %})"></div>
                <div class="swiper-slide" style="background-image:url({% static 'images/girls/sunny5.jpg' %})"></div>
                <div class="swiper-slide" style="background-image:url({% static 'images/girls/sunny8.jpg' %})"></div>
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
        </div>
    </div>

</div>

<script>
    $("#regisetering__account").click(()=>{
        $(".loading-screen").show()
    })
    var swiper = new Swiper('.swiper-container1', {
        effect: 'cube',
        grabCursor: true,
        speed: 1500,
        autoplay: {
            delay: 3000
        },
        cubeEffect: {
            shadow: true,
            slideShadows: true,
            shadowOffset: 20,
            shadowScale: 0.94,
        },
        pagination: {
            el: '.swiper-pagination',
        },
    });


    $("#id_username").attr("placeholder","Username")
    $("#id_email").attr("placeholder", "Email")
    $("#id_phone").attr("placeholder", "Mobile Number")
    $("#id_first_name").attr("placeholder", "First Name")
    $("#id_last_name").attr("placeholder", "Last Name")
    $("#id_address").attr("placeholder", "Address")
    $("#id_zipcode").attr("placeholder", "Zipcode")
    $("#id_city").attr("placeholder", "City")
    $("#id_state").attr("placeholder", "State")
    $("#id_password1").attr("placeholder", "Enter Password")
    $("#id_password2").attr("placeholder", "Confirm Password")

    document.getElementById("id_address").setAttribute("placeholder", "Address")
    document.getElementById('id_city').setAttribute('readonly', true);
    document.getElementById('id_state').setAttribute('readonly', true);

    var uname = document.getElementById("id_username")
    const feedbackField = document.getElementById("valid-the-username")
    uname.addEventListener("keyup", (e) => {
        const usernameVal = e.target.value;
        url = "/username_validation/"
        if (usernameVal.length > 0) {
            fetch(url, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify({
                    "username": usernameVal
                })

            }).then(res => res.json()).then(data => {
                if (data.UsernameError) {
                    uname.classList.add("is-invalid")
                    feedbackField.innerHTML = `<p>${data.UsernameError}</p>`
                } else {
                    uname.classList.remove("is-invalid")
                    feedbackField.innerHTML = `<p></p>`
                }
            })
        } else {
            uname.classList.remove("is-invalid")
            feedbackField.innerHTML = `<p></p>`
        }
    })



    var uemail = document.getElementById("id_email")
    const feedbackField1 = document.getElementById("valid-the-email")
    uemail.addEventListener("keyup", (e) => {
        const useremailVal = e.target.value;
        url = "/useremail_validation/"
        if (useremailVal.length > 0) {
            fetch(url, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify({
                    "useremail": useremailVal
                })

            }).then(res => res.json()).then(data => {
                if (data.UserEmailError) {
                    uemail.classList.add("is-invalid")
                    feedbackField1.innerHTML = `<p>${data.UserEmailError}</p>`
                } else {
                    uemail.classList.remove("is-invalid")
                    feedbackField1.innerHTML = `<p></p>`
                }
            })
        } else {
            uemail.classList.remove("is-invalid")
            feedbackField1.innerHTML = `<p></p>`
        }
    })



    var zipcode = document.getElementById("id_zipcode")
    var feedbackField2 = document.getElementById("valid-the-zipcode")
    zipcode.addEventListener("keyup", (e) => {
        const zipcode_ = e.target.value;
        url = "/postalcode_validation/"
        if (zipcode_.length >= 6) {
            fetch(url, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify({
                    "postalcode": zipcode_
                })

            }).then(res => res.json()).then(data => {
                if (data.POSTAL_CODE) {
                    zipcode.classList.remove("is-invalid")
                    feedbackField2.innerHTML = `<p></p>`
                    document.getElementById('id_city').value = data.area_info.data.city
                    document.getElementById('id_state').value = data.area_info.data.state
                } else {
                    zipcode.classList.add("is-invalid")
                    feedbackField2.innerHTML = `<p>We are not rechable</p>`
                    document.getElementById('id_city').value = ""
                    document.getElementById('id_state').value = ""
                }
            })
        } else {
            zipcode.classList.remove("is-invalid")
            feedbackField2.innerHTML = `<p></p>`
            document.getElementById('id_city').value = ""
            document.getElementById('id_state').value = ""
        }
    }
    )

</script>

{% endblock %}