DjangoEcommerce/AdminModel/urls.py
from django.urls import path
from .views import *
urlpatterns = [
    path("", all_esite_details),
    path("get_users_name/", get_users_name),
    path("get_orders/", get_order_by_trns_id),
    path("get_deliverd_or_pending/", get_deliverd_or_pending),
    path("get_address_for_popup/", get_address_forpopup),
    path("cust_detail/<int:id>/", cust_detail, name="cust_detail"),
    path("get_reviews_onstars/", get_reviews_onstars)
]

DjangoEcommerce/EcommerceProject/urls.py
from django.contrib import admin
from django.urls import path,include
from EcommerceApp.views import *
from django.conf.urls.static import static
from django.conf import settings


from django.views.static import serve
from django.urls import re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', store, name="store"),
    path("cart/", cart, name="cart"),
    path("signup/", signupForm, name="signup"),
    path("logout/",logoutUser,name="logout"),
    path('login/', loginPage, name="login"),
    path("wears/", include("EcommerceApp.urls")),
    path("update/", update_item, name="update"),
    path("cart/", cart, name="cart"),
    path("chekcout/", checkout, name="checkout"),
    path("process_order/", processOrder, name="process_order"),
    path("update_address/", updateAddress, name="updateAddress"),
    path("update_review/", update_review, name="update_review"),
    path("activate_email/<uidb64>/<token>/", activateEmailAccount, name="activate_email"),
    path("request_reset_email/", RequestResetPasswordView.as_view(), name="request_reset_email"),
    path("set_new_password/<uidb64>/<token>/", SetNewPasswordView.as_view(), name="set_new_password"),
    path("username_validation/", UserNameValidation.as_view(), name="username_validation"),
    path("useremail_validation/", UserEmailValidation.as_view(), name="useremail_validation"),
    path("postalcode_validation/",PostalCodeValidation.as_view(),name="postalcode_validation"),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),

    path("AdminModel/",include('AdminModel.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT) 

DjangoEcommerce/EcommerceApp/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from .models import Customer
from django import forms
import requests

class CreateUserForm(UserCreationForm):
    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
    )
    phone = forms.CharField(validators=[phone_regex], max_length=17)
    address = forms.CharField(widget=forms.Textarea)
    city = forms.CharField(max_length=50)
    zipcode = forms.IntegerField()
    state = forms.CharField(max_length=80)

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "phone",
            "address",
            "city",
            "zipcode",
            "state",
        ]
    def clean_zipcode(self):
        url = "http://127.0.0.1:4545/%d/" % (self.cleaned_data['zipcode'])
        data = requests.get(url)
        data = data.json()
        if data['data']['is_available'] == False:
            raise forms.ValidationError("We are unreachable for pincode : " + str(self.cleaned_data['zipcode']))
        else:
            return self.cleaned_data['zipcode']
        



        
class ShippingAddressForm(forms.ModelForm):
    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
    )
    phone = forms.CharField(validators=[phone_regex], max_length=17)
    class Meta:
        model = ShippingAddress
        fields = [
            'address',
            'phone',
            'city',
            'state',
            'zipcode'
        ]
    def clean_zipcode(self):
        url = "http://127.0.0.1:4545/%d/" % (self.cleaned_data['zipcode'])
        data = requests.get(url)
        data = data.json()
        if data['data']['is_available'] == False:
            raise forms.ValidationError("We are unreachable for pincode : " + str(self.cleaned_data['zipcode']))
        else:
            return self.cleaned_data['zipcode']


        
class CheckPincode(forms.Form):
    Postal_Code = forms.IntegerField()

DjangoEcommerce/templates/wears/paithani.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
<h1 class="products__header__title"> paithanis</h1>
<div class="my__container__products">
    {% for i in paithanis %}
    <div class="flip__card">
        <div class="flip__card__inner">
            <div class="flip__card__front">
                <img src="{{i.imageurl}}" alt="Avatar" style="width:300px;height:300px;">
            </div>
            <div class="flip__card__back">
                <span class="flip__card__back__info">
                    <h1>{{i.name}}</h1>
                    <h3><i class="fas fa-rupee-sign"></i> {{i.price}}/-<a href="{% url 'product_details' i.id %}">View<i class="fas fa-external-link-alt"></i></a></h3>
                </span>
                <span class="flip__card__back__buttons">
                    <button data-product={{i.id}} data-action="add" data-to-buy="buy"
                        class="add-to-cart btn update-cart" style="transition: 0.4s;"><i class="fas fa-rupee-sign"></i> &nbsp;
                        Buy Now</button>
                    <button data-product={{i.id}} data-action="add" class="add-to-cart btn update-cart" style="transition: 0.4s;"><i
                            class="fa fa-shopping-cart"></i> &nbsp; Add to
                        Cart</button>
                </span>
            </div>
        </div>
    </div>
    {% endfor %}
    
</div>

{% endblock %}

DjangoEcommerce/templates/wears/product_details.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
{% load makerange from templatefilters %}
{% load checkstring from templatefilters %}
{% load orderbydate from templatefilters %}

<div class="my__container__productdetails__page">
    <div class="my__container__productdetails__page__image">
        <div class="swiper-container">
            <div class="swiper-wrapper">
                {% for image in images %}
                <div class="swiper-slide" style="background-image:url({{image}})"></div>
                {% endfor %}
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
        </div>
        <div class="add__buy__buttons__product__details">
            <button data-product={{product.id}} data-action="add" data-to-buy="buy"
                class="add-to-cart btn update-cart" style="transition: 0.4s;"><i class="fas fa-rupee-sign"></i> &nbsp;
                Buy Now</button>
            <button data-product={{product.id}} data-action="add" class="add-to-cart btn update-cart" style="transition: 0.4s;"><i
                    class="fa fa-shopping-cart"></i> &nbsp; Add to
                Cart</button>
        </div>
    </div>
    <div class="my__container__productdetails__page__information">
        <p class="specification__para">
            <span>Specifications</span>
        </p>
        <div class="product__specifications__container">
            {% for message in messages %}
            {% if message|checkstring %}
            <p id="messages" style="color: green; margin-bottom: 5px;">{{message}}</p>
            {% else %}
            <p id="messages" style="color: red; margin-bottom: 5px;">{{message}}</p>
            {% endif %}
            {% endfor %}
            <div class="postal__code__validations__box">
                <form method="POST">
                    {% csrf_token %}
                    {{form}}
                    <button type="submit" class="btn btn-light">Check</button>
                </form>
            </div> <br> 
            <h1>Product Details</h1>
            <hr> <br>
            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold">
                    Name
                </div>
                <div class="product__specifications__item">
                    {{product.name}}
                </div>
            </div>
            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold">
                    Fabric
                </div>
                <div class="product__specifications__item">
                    {{product.fabric}}
                </div>
            </div>
            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold">
                    Pattern
                </div>
                <div class="product__specifications__item">
                    {{product.pattern}}
                </div>
            </div>
            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold">
                    Color
                </div>
                <div class="product__specifications__item">
                    {{product.color}}
                </div>
            </div>
            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold">
                    Num of set
                </div>
                <div class="product__specifications__item">
                    {{product.in_the_pack}}
                </div>
            </div>
            <br> <br>
            <h1>Additional Details</h1>
            <hr> <br>

            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold">
                    Style
                </div>
                <div class="product__specifications__item product__specifications__item__freedom">
                    {{product.style}}
                </div>
            </div>

            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold">
                    Category
                </div>
                <div class="product__specifications__item product__specifications__item__freedom">
                    {{product.category}}
                </div>
            </div>
            <br> <br>
            <h1>Price</h1>
            <hr> <br>
            <div class="product__specifications">
                <div class="product__specifications__item product__specifications__item__bold" style="color: #f79831; font-size: 1.5em;">
                    ₹ {{product.price}}/-
                </div>
            </div>
            
            
        </div>
    </div>
</div>

{% if request.user.is_authenticated %}
<div class="my__container__review__box">
    <form action="">
        <textarea id="rating-view" name=""></textarea>
        <div class="my__container__review__box__stars">
            <span class="star-rating star-rating-pm my__container__review__box__stars__span">
                <span>
                    <span class="far fa-star" data-rating="1"></span>
                    <span class="far fa-star" data-rating="2"></span>
                    <span class="far fa-star" data-rating="3"></span>
                    <span class="far fa-star" data-rating="4"></span>
                    <span class="far fa-star" data-rating="5"></span>
                    <input type="hidden" name="whatever1" class="rating-value">
                </span>
                <span>
                    <input id="product-review-button" class="btn btn-warning" type="button" value="Submit">
                </span>
            </span>
        </div>
    </form>
</div>
{% endif %}


{% for product_review in product_reviews|orderbydate %}
<div class="my__container__user__given__review">
    <div class="user__information__for__review">
        <article>
            <span>User</span> : {{product_review.customer.name}} <span>Date</span> : {{product_review.date|date:"M d, Y"}}
        </article>
        <article>
            <span>Ratings </span>:
            {% for value in product_review.stars|makerange %}
            <i class="fa fa-star" style="color: #f79831;"></i>
            {% endfor %}
        </article>
    </div>
    <div class="actual__review">
        <span>{{product_review.review}}</span>
    </div>
</div>
{% endfor %}



<div class="product__details__recommendations">
    <div class="example__frame">
        <div id="intro6" class="slider glide">
            <div class="slider__track glide__track" data-glide-el="track">
                <ul class="slider__slides glide__slides">
                    {% for i in all_slider_products_list %}
                    <li class="slider__frame glide__slide" style="background-image: url({{i.imageurl}})">
                        <div class="bg__img__info__pricing">
                            <div class="bg__img__product__info">
                                <h1>{{i.name}} </h1>
                                <h1>{{i.price}}<span><a href="{% url 'product_details' i.id %}">View<i class="fas fa-external-link-alt"></i></a></span>
                                </h1>
                            </div>
                            <div class="bg__img__buttons">
                                <button style="margin-left: 15px;" data-product={{i.id}} data-action="add"
                                data-to-buy="buy" class="add-to-cart btn update-cart" style="transition: 0.4s;">
                                    <i class="fas fa-rupee-sign"></i> &nbsp;
                                    Buy Now</button>
                                <button data-product={{i.id}} data-action="add" class="add-to-cart btn update-cart"
                                    style="transition: 0.4s;"><i class="fa fa-shopping-cart"></i> &nbsp; Add to
                                    Cart</button>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <div data-glide-el="controls">
                <button class="slider__arrow slider__arrow--prev glide__arrow glide__arrow--prev" data-glide-dir="<">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
                        <path d="M0 12l10.975 11 2.848-2.828-6.176-6.176H24v-3.992H7.646l6.176-6.176L10.975 1 0 12z" />
                    </svg>
                </button>

                <button class="slider__arrow slider__arrow--next glide__arrow glide__arrow--next" data-glide-dir=">">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
                        <path
                            d="M13.025 1l-2.847 2.828 6.176 6.176h-16.354v3.992h16.354l-6.176 6.176 2.847 2.828 10.975-11z" />
                    </svg>
                </button>
            </div>

        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function (event) {
        var glide = new Glide('#intro6', {
            type: 'carousel',
            perView: 4,
            focusAt: 'center',
            breakpoints: {
                1500: {
                    perView: 4
                },
                1200: {
                    perView: 3
                },
                800: {
                    perView: 2
                },
                480: {
                    perView: 1
                }
            }
        })

        glide.mount()

    })
</script>

<script>
    $("#id_Postal_Code").attr("placeholder","Check your postal code here.")
    var swiper = new Swiper('.swiper-container', {
        effect: 'cube',
        speed: 1500,
        autoplay: {
            delay: 3000
        },
        grabCursor: true,
        cubeEffect: {
            shadow: true,
            slideShadows: true,
            shadowOffset: 20,
            shadowScale: 0.94,
        },
        pagination: {
            el: '.swiper-pagination',
        },
    });
    var product_review_button = $("#product-review-button")
    product_review_button.click(() => {
        if (user === "AnonymousUser") {
            alert("Please login to add the review.")
        } else {
            var customer = user;
            var product = "{{product.id}}"
            var review = $("#rating-view").val()
            var stars = $("span.fas").length
            console.log(stars)
            var url = "/update_review/"
            if (stars < 1) {
                alert("Please rate the product.")
            } else {
                if(review.length < 10) {
                    alert("Please review the product with some words.")
                }else {
                    fetch(url, {
                        method: 'POST',
                        headers: {
                            "Content-Type": "application/json",
                            'X-CSRFToken': csrftoken
                        },
                        body: JSON.stringify({
                            'customer': customer,
                            'productid': product,
                            'review': review,
                            'stars': stars,
                        })
                    }).then((response) => {
                        return response.json()
                    }).then((data) => {
                        console.log('data', data);
                        location.reload()
                    })
                }
            }
        }
    })
</script>
{% endblock %}

DjangoEcommerce/templates/wears/searched_products.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
<style>
    .searched__products__not__found {
        position: absolute;
        top: 30%; 
        left: 50%;
        transform: translate(-50%, -50%);
        box-shadow: none;
        
    }

    .searched__products__not__found h1 {
        font-weight: 300;
        color: orange;
        text-align: center;
        width: 400px;
    }
    @media (max-width: 450px) {
         .searched__products__not__found h1 {
             width: 250px;
             
         }
    }
</style>
{% if products %}
<div class="my__container__products">
    {% for i in products %}
    <div class="flip__card">
        <div class="flip__card__inner">
            <div class="flip__card__front">
                <img src="{{i.imageurl}}" alt="Avatar" style="width:300px;height:300px;">
            </div>
            <div class="flip__card__back">
                <span class="flip__card__back__info">
                    <h1>{{i.name}}</h1>
                    <h3>{{i.price}}<a href="{% url 'product_details' i.id %}">View<i
                                class="fas fa-external-link-alt"></i></a></h3>
                </span>
                <span class="flip__card__back__buttons">
                    <button data-product={{i.id}} data-action="add" data-to-buy="buy" class="add-to-cart btn update-cart"
                        style="transition: 0.4s;"><i class="fas fa-rupee-sign"></i> &nbsp;
                        Buy Now</button>
                    <button data-product={{i.id}} data-action="add" class="add-to-cart btn update-cart"
                        style="transition: 0.4s;"><i class="fa fa-shopping-cart"></i> &nbsp; Add to
                        Cart</button>
                </span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% else %}
<div class="searched__products__not__found">
   <h1>Searched products not found !</h1>
</div>
{% endif %}


{% endblock %}

DjangoEcommerce/templates/wears/semi_paithani.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
<h1 class="products__header__title"> semi paithanis</h1>
<div class="my__container__products">
    {% for i in semi_paithanis %}
    <div class="flip__card">
        <div class="flip__card__inner">
            <div class="flip__card__front">
                <img src="{{i.imageurl}}" alt="Avatar" style="width:300px;height:300px;">
            </div>
            <div class="flip__card__back">
                <span class="flip__card__back__info">
                    <h1>{{i.name}}</h1>
                    <h3><i class="fas fa-rupee-sign"></i> {{i.price}}/-<a href="{% url 'product_details' i.id %}">View<i class="fas fa-external-link-alt"></i></a></h3>
                </span>
                <span class="flip__card__back__buttons">
                    <button data-product={{i.id}} data-action="add" data-to-buy="buy"
                        class="add-to-cart btn update-cart" style="transition: 0.4s;"><i class="fas fa-rupee-sign"></i> &nbsp;
                        Buy Now</button>
                    <button data-product={{i.id}} data-action="add" class="add-to-cart btn update-cart" style="transition: 0.4s;"><i
                            class="fa fa-shopping-cart"></i> &nbsp; Add to
                        Cart</button>
                </span>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

DjangoEcommerce/templates/wears/silk_wear.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
<h1 class="products__header__title"> silk sarees</h1>
<div class="my__container__products">
    {% for i in silk_sarees %}
    <div class="flip__card">
        <div class="flip__card__inner">
            <div class="flip__card__front">
                <img src="{{i.imageurl}}" alt="Avatar" style="width:300px;height:300px;">
            </div>
            <div class="flip__card__back">
                <span class="flip__card__back__info">
                    <h1>{{i.name}}</h1>
                    <h3><i class="fas fa-rupee-sign"></i> {{i.price}}/-<a href="{% url 'product_details' i.id %}">View<i class="fas fa-external-link-alt"></i></a></h3>
                </span>
                <span class="flip__card__back__buttons">
                <button data-product={{i.id}} data-action="add" data-to-buy="buy"
                    class="add-to-cart btn update-cart" style="transition: 0.4s;"><i class="fas fa-rupee-sign"></i> &nbsp;
                    Buy Now</button>
                <button data-product={{i.id}} data-action="add" class="add-to-cart btn update-cart" style="transition: 0.4s;"><i
                        class="fa fa-shopping-cart"></i> &nbsp; Add to
                    Cart</button>
                </span>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

DjangoEcommerce/templates/wears/traditional_wear.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
<h1 class="products__header__title"> traditionals</h1>
<div class="my__container__products">
    {% for i in traditionals %}
    <div class="flip__card">
        <div class="flip__card__inner">
            <div class="flip__card__front">
                <img src="{{i.imageurl}}" alt="Avatar" style="width:300px;height:300px;">
            </div>
            <div class="flip__card__back">
                <span class="flip__card__back__info">
                    <h1>{{i.name}}</h1>
                    <h3><i class="fas fa-rupee-sign"></i> {{i.price}}/-<a href="{% url 'product_details' i.id %}">View<i class="fas fa-external-link-alt"></i></a></h3>
                </span>
                <span class="flip__card__back__buttons">
                    <button data-product={{i.id}} data-action="add" data-to-buy="buy"
                        class="add-to-cart btn update-cart" style="transition: 0.4s;"><i class="fas fa-rupee-sign"></i> &nbsp;
                        Buy Now</button>
                    <button data-product={{i.id}} data-action="add" class="add-to-cart btn update-cart" style="transition: 0.4s;"><i
                            class="fa fa-shopping-cart"></i> &nbsp; Add to
                        Cart</button>
                </span>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}

DjangoEcommerce/templates/wears/western_wear.html
{% extends '../base.html' %}
{% block content %}
{% load static %}
<h1 class="products__header__title"> westerns</h1>
<div class="my__container__products">
    {% for i in westerns %}
    <div class="flip__card">
        <div class="flip__card__inner">
            <div class="flip__card__front">
                <img src="{{i.imageurl}}" alt="Avatar" style="width:300px;height:300px;">
            </div>
            <div class="flip__card__back">
                <span class="flip__card__back__info">
                    <h1>{{i.name}}</h1>
                    <h3><i class="fas fa-rupee-sign"></i> {{i.price}}/-<a href="{% url 'product_details' i.id %}">View<i class="fas fa-external-link-alt"></i></a></h3>
                </span>
                <span class="flip__card__back__buttons">
                    <button data-product={{i.id}} data-action="add" data-to-buy="buy"
                        class="add-to-cart btn update-cart" style="transition: 0.4s;"><i class="fas fa-rupee-sign"></i> &nbsp;
                        Buy Now</button>
                    <button data-product={{i.id}} data-action="add" class="add-to-cart btn update-cart" style="transition: 0.4s;"><i
                            class="fa fa-shopping-cart"></i> &nbsp; Add to
                        Cart</button>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

{% endblock %}